services:
  mc-server:
    image: ${IMAGE_NAME}:${MC_VERSION}
    pull_policy: never
    build:
      target: minecraft-server
      dockerfile: scripts/Dockerfile.glibc
      args:
        - JAVA_VERSION=${JAVA_VERSION}
        - SERVER_LINK=${SERVER_LINK}
    stdin_open: true
    user: ${UID:-65532}:${GID:-65532}
    volumes:
      - ./out:/mnt/server-files/
      #- ./server.jar:/home/server.jar
    tty: true
    ports:
      - "25565:25565"
    entrypoint: java
    command: -Xmx1024M -Xms1024M -jar /home/server.jar --nogui
