name: Bug Report
description: Create a report on a broken feature to help improve the software.
title: "[BUG] - "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the required sections to help us reproduce and fix the bug/issue.
  - type: textarea
    id: description
    attributes:
      label: "# Describe the bug"
      placeholder: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "# Reproduction steps"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "# Expected Behaviour"
      placeholder: A description of what the correct behaviour should be.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: "# Additional Context"
      placeholder: Add any other context that can help with the problem.
  - type: dropdown
    attributes:
      label: "## Select operating system version (if relevant)"
      options:
        - Windows
        - Mac
        - Linux
  - type: input
    attributes:
      label: "## Related Minecraft Version (if relevant)"
