ARG JAVA_VERSION=8

# Generate the custom JRE as required.
FROM eclipse-temurin:${JAVA_VERSION}-alpine AS jre-dev
WORKDIR /home

COPY ./scripts/gen_jre.sh /home/setup.sh
RUN apk add --no-cache \
    bash \
    binutils

SHELL ["/bin/bash"]
RUN ./setup.sh

# Container to host the new JRE.
FROM alpine:latest AS server-base

# Include optional libs for minecraft server functionality.
RUN apk add --no-cache \
    eudev-libs

ENV JAVA_HOME=/usr/local
COPY --from=jre-dev /home/jre $JAVA_HOME

ARG UNAME=user
ARG GNAME=user
ARG UID=1000
ARG GID=1000

# Create a group and a system user in a single RUN instruction to reduce image layers
RUN addgroup -S -g $GID $GNAME && adduser -S -D -u $UID -G $GNAME $UNAME
WORKDIR /home/${UNAME}

# Setup the vanilla minecraft server to be ready to run.
FROM server-base AS minecraft-server
ARG SERVER_LINK
RUN wget -O /home/server.jar $SERVER_LINK

ARG UNAME=user
USER ${UNAME}

CMD ["java", "-jar", "/home/server.jar", "--nogui"]

# Only have the environment setup for local downloaded server.
# You should bind the "server.jar" file to "/home/server.jar" if using this stage.
# This stage is for experimental purposes.
FROM server-base AS env-base
ARG UNAME=user
USER ${UNAME}

CMD ["java", "-jar", "/home/server.jar", "--nogui"]
