ARG JAVA_VERSION=8

# Generate the custom JRE as required.
FROM eclipse-temurin:${JAVA_VERSION}-jdk AS jre-dev
WORKDIR /home
COPY ./scripts/gen_jre.sh /home/setup.sh
RUN ./setup.sh

FROM debian:stable-slim AS updated-apts
RUN apt-get update

# Start of the build base that installs all needed libraries to prepare final image.
FROM updated-apts AS build-base
ARG MINECRAFT_EULA
ENV MINECRAFT_EULA ${MINECRAFT_EULA}
WORKDIR /opt
COPY ./scripts/install_base_glibc.sh /opt/install.sh
RUN ./install.sh

# Separate stage that downloads the "server.jar" file.
FROM updated-apts AS server-download
RUN apt-get install -y --no-install-recommends \
    wget \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ARG SERVER_LINK
RUN wget -O /home/server.jar $SERVER_LINK

# The image that will be used to host the container.
FROM scratch AS server-base
COPY --from=build-base /opt/root /

ENV JAVA_HOME=/usr/local
COPY --from=jre-dev /home/jre $JAVA_HOME

# Use non-root user to conform to Principle of Least Privilege (PoLP)
USER 65532:65532
WORKDIR /mnt/server-files/65532_65532

# Setup the vanilla minecraft server to be ready to run.
FROM server-base AS minecraft-server
COPY --from=server-download /home/server.jar /home/server.jar
EXPOSE 25565
ENTRYPOINT ["java"]
CMD ["-jar", "/home/server.jar", "--nogui"]

# Only have the environment setup for local downloaded server.
# You should bind the "server.jar" file to "/home/server.jar" if using this stage.
# This stage is for experimental purposes.
FROM server-base AS env-base
ENTRYPOINT ["java"]
